# Sample config for Prometheus.

global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'example'

# alerting rules
# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
 - 'alert.rules.yaml'
  # - "first.rules"
  # - "second.rules"
alerting:
  alertmanagers:
    - static_configs:
      - targets: ['alertmanager:9093']
# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'power'
    scrape_interval: 5s
    scrape_timeout: 5s
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: ['power-exporter:8080']
  - job_name: 'lede'
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: ['lede:9100']
  - job_name: 'cpu_power'
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: 
        - summit.glek.net:9999
        - summit.glek.net:9100
  - job_name: 'node-ping'
    metrics_path: /probe
    params:
      module: [icmp]
    static_configs:
      - targets: &ping_targets
        - my.xfinity.com
        # - garage-ap
        - speedtest.netflix.com
        # - coop
        - backcam
        - porchcam
        - openpilot
        - '192.168.1.206'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__address__]
        target_label: instance
      - source_labels: []
        target_label: __address__
        replacement: node-ping:3000
  - job_name: 'node'
    file_sd_configs:
    - files:
      - '/tmp/file_sd.json'
